### ISSUE TITLE
Question about the calculate of posterior expectation

### ISSUE THREAD

**Issue by zhoutianyang2002** [Yoruko-Tang/FedCor#2]
Dear author,

I am a junior student and I am a newbie of FL. I am not really sure about the meaning of this formula(10):

$$k^{*}=\underset{k}{argmin} \sum_{i} p_{i} \tilde{\mu}_{i}^{t}(\Delta \hat{l}_{k}^{t})$​$

Specifically, I do not understand how the posterior expectation is calculated here. Could you provide a specific example or a formula for calculating $ \tilde{\mu}_{i}^{t}(\Delta \hat{l}_{k}^{t})$ ? Is this is a function which input is $\Delta \hat{l}_{k}^{t}$? However, why can we use the expected loss value of the k-th client to calculate the expected average loss of the i-th client?

Sorry to bother you, this may be a foolish question but I am not familiar with Bayesian optimization. Thanks a lot!

**Comment by zhoutianyang2002** [comment]
sorry, this may have some mistakes about latex. here this the question in picture.
<img width="716" alt="image" src="https://github.com/Yoruko-Tang/FedCor/assets/88141502/f31c2ca7-7347-4af7-bc2c-2b88701547ac">

**Comment by Yoruko-Tang** [comment]
Hi, 

In the paper, we observe that the loss changes of different clients, i.e., $\Delta l = [\Delta l_1,\cdots,\Delta l_N]$, jointly follow a Multivariate Gaussian Distribution. Based on the observation and the posterior formulation of the Multivariate Gaussian Distribution, we can calculate the posterior mean conditioned on one (or multiple) measured dimension of the multivariate random variable, i.e., $\Delta \hat l_k$. The posterior formulation can be found on [Wikipedia https://en.wikipedia.org/wiki/Multivariate_normal_distribution](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#:~:text=Conditional%20distributions). The posterior formulations for the mean and covariance are also used in Eq. (42) and Eq. (45) in the Appendix of our paper. You will find that the posterior mean $\tilde \mu$ is actually a function of the condition $\Delta \hat l_k$.

I hope this information can help you.

**Comment by zhoutianyang2002** [comment]
> Hi,
> 
> In the paper, we observe that the loss changes of different clients, i.e., Δl=[Δl1,⋯,ΔlN], jointly follow a Multivariate Gaussian Distribution. Based on the observation and the posterior formulation of the Multivariate Gaussian Distribution, we can calculate the posterior mean conditioned on one (or multiple) measured dimension of the multivariate random variable, i.e., Δl^k. The posterior formulation can be found on [Wikipedia https://en.wikipedia.org/wiki/Multivariate_normal_distribution](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#:~:text=Conditional%20distributions). The posterior formulations for the mean and covariance are also used in Eq. (42) and Eq. (45) in the Appendix of our paper. You will find that the posterior mean μ~ is actually a function of the condition Δl^k.
> 
> I hope this information can help you.

I understand now. Thank you for your clear and helpful reply! Best wishes!
